;;Session timings
Xsession1_start=XHKG:09:30, XSES:09:00
Xsession1_end=XHKG:13:00, XSES:12:00
Xsession2_start=XHKG:14:00, XSES:13:00
Xsession2_end=XHKG:16:00, XSES:17:00
Xsession3_start=XHKG:16:00, XSES:17:06
Xsession3_end=XHKG:16:10, XSES:17:16
